# Generated by Django 5.0.3 on 2024-03-19 23:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=300, unique=True)),
                ('secondary_title', models.CharField(blank=True, max_length=300, null=True)),
                ('description_title', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(default=0)),
                ('doors', models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5)])),
                ('engine', models.CharField(choices=[('nafta', 'nafta'), ('diesel', 'diesel'), ('electrico', 'electrico')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('main_image', models.FileField(blank=True, max_length=200, null=True, upload_to='cars/main_images')),
                ('main_thumbnail', models.ImageField(blank=True, max_length=200, null=True, upload_to='cars/main_thumbnail_images/')),
                ('secondary_image', models.FileField(blank=True, max_length=200, null=True, upload_to='cars/secondary_images')),
                ('secondary_thumbnail', models.ImageField(blank=True, max_length=200, null=True, upload_to='cars/secondary_thumbnail_images/')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.category')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.color')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, max_length=200, null=True, upload_to='cars/feature_images')),
                ('thumbnail', models.ImageField(blank=True, max_length=200, null=True, upload_to='cars/feature_thumbnail_images/')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, max_length=200, null=True, upload_to='cars/slider_images')),
                ('thumbnail', models.ImageField(blank=True, max_length=200, null=True, upload_to='cars/slider_thumbnail_images/')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
    ]
